namespace :db do
  desc "Fill database with schools"
  task populate: :environment do
    School.create!(school_id: 0, name:'Acadia Divinity College')
    School.create!(school_id: 0, name:'Acadia University')
    School.create!(school_id: 0, name:'Académie Julien Inc.')
    School.create!(school_id: 0, name:'Adult Education Centre')
    School.create!(school_id: 0, name:'Alberta College of Art and Design')
    School.create!(school_id: 0, name:'Algoma University College')
    School.create!(school_id: 0, name:'Assiniboine Community College')
    School.create!(school_id: 0, name:'Assumption University')
    School.create!(school_id: 0, name:'Athabasca University')
    School.create!(school_id: 0, name:'Atkinson College')
    School.create!(school_id: 0, name:'Atlantic School of Theology')
    School.create!(school_id: 0, name:'Atlantic Veterinary College, University of Prince Edward Island Nova Scotia')
    School.create!(school_id: 0, name:'Augustana University College')
    School.create!(school_id: 0, name:'Aurora College')
    School.create!(school_id: 0, name:'Bethany Bible College')
    School.create!(school_id: 0, name:'Bishop’s University')
    School.create!(school_id: 0, name:'Bow Valley College')
    School.create!(school_id: 0, name:'Brandon University')
    School.create!(school_id: 0, name:'Brescia College')
    School.create!(school_id: 0, name:'British Columbia Institute of Technology')
    School.create!(school_id: 0, name:'Brock University')
    School.create!(school_id: 0, name:'Camosun College')
    School.create!(school_id: 0, name:'Campion College')
    School.create!(school_id: 0, name:'Canadian Baptist Seminary')
    School.create!(school_id: 0, name:'Canadian Bible College')
    School.create!(school_id: 0, name:'Canadian Coast Guard College')
    School.create!(school_id: 0, name:'Canadian Mennonite University')
    School.create!(school_id: 0, name:'Canadian Nazarene College')
    School.create!(school_id: 0, name:'Canadian Theological Seminary')
    School.create!(school_id: 0, name:'Canadian University College')
    School.create!(school_id: 0, name:'Cancer Care Manitoba')
    School.create!(school_id: 0, name:'Canterbury College')
    School.create!(school_id: 0, name:'Capilano College')
    School.create!(school_id: 0, name:'Carleton University')
    School.create!(school_id: 0, name:'Carlton Trail Regional College')
    School.create!(school_id: 0, name:'Central Pentecostal College')
    School.create!(school_id: 0, name:'Coady International Institute')
    School.create!(school_id: 0, name:'College of New Caledonia')
    School.create!(school_id: 0, name:'College of the North Atlantic')
    School.create!(school_id: 0, name:'College of the Rockies')
    School.create!(school_id: 0, name:'Collège de l’Acadie')
    School.create!(school_id: 0, name:'Collège d’Alfred')
    School.create!(school_id: 0, name:'Collège Universitaire de Hearst')
    School.create!(school_id: 0, name:'Collège Universitaire de Saint-Boniface')
    School.create!(school_id: 0, name:'Community Colleges and Related institutions by jurisdiction')
    School.create!(school_id: 0, name:'Concordia Lutheran Theological College')
    School.create!(school_id: 0, name:'Concordia University College of Alberta')
    School.create!(school_id: 0, name:'Concordia University')
    School.create!(school_id: 0, name:'Conrad Grebel College')
    School.create!(school_id: 0, name:'Cross Cancer Institute, School of Radiation Therapy')
    School.create!(school_id: 0, name:'Cumberland Regional College')
    School.create!(school_id: 0, name:'Cypress Hills Regional College')
    School.create!(school_id: 0, name:'Dalhousie University Polytechnic')
    School.create!(school_id: 0, name:'Dalhousie University')
    School.create!(school_id: 0, name:'Douglas College')
    School.create!(school_id: 0, name:'Emily Carr Institute of Art & Design')
    School.create!(school_id: 0, name:'Emmanuel Bible College')
    School.create!(school_id: 0, name:'Erindale College')
    School.create!(school_id: 0, name:'Fairview College')
    School.create!(school_id: 0, name:'Fisheries and Marine Institute of Memorial University Harlow Campus - Memorial University')
    School.create!(school_id: 0, name:'Glendon College')
    School.create!(school_id: 0, name:'Grande Prairie Regional College')
    School.create!(school_id: 0, name:'Grant MacEwan Community College')
    School.create!(school_id: 0, name:'Health Sciences Centre')
    School.create!(school_id: 0, name:'Holland College')
    School.create!(school_id: 0, name:'Holy Redeemer College')
    School.create!(school_id: 0, name:'Huntington University')
    School.create!(school_id: 0, name:'Huron University College')
    School.create!(school_id: 0, name:'Institute of Indigenous Government')
    School.create!(school_id: 0, name:'Iona College')
    School.create!(school_id: 0, name:'Justice Institute of British Columbia')
    School.create!(school_id: 0, name:'Kemptville College of Agricultural Technology Ridgetown College')
    School.create!(school_id: 0, name:'King’s College')
    School.create!(school_id: 0, name:'King’s University College')
    School.create!(school_id: 0, name:'Knox College')
    School.create!(school_id: 0, name:'Kwantlen University College')
    School.create!(school_id: 0, name:'Lakeland College')
    School.create!(school_id: 0, name:'Lakeland College, Lloydminster Campus')
    School.create!(school_id: 0, name:'Lakeland College, Vermilion Campus')
    School.create!(school_id: 0, name:'Langara College')
    School.create!(school_id: 0, name:'Laurentian University')
    School.create!(school_id: 0, name:'Lethbridge Community College')
    School.create!(school_id: 0, name:'Luther College')
    School.create!(school_id: 0, name:'Lutheran Theological Seminary')
    School.create!(school_id: 0, name:'L’École Technique et Professionnelle')
    School.create!(school_id: 0, name:'Malaspina University College')
    School.create!(school_id: 0, name:'Maritime Forest Ranger School')
    School.create!(school_id: 0, name:'McGill University')
    School.create!(school_id: 0, name:'McMaster Divinity College')
    School.create!(school_id: 0, name:'McMaster University - Conestoga')
    School.create!(school_id: 0, name:'McMaster University - Mohawk')
    School.create!(school_id: 0, name:'McMaster University')
    School.create!(school_id: 0, name:'Medicine Hat College')
    School.create!(school_id: 0, name:'Memorial University of Newfoundland')
    School.create!(school_id: 0, name:'Memorial University Off Campus Centres')
    School.create!(school_id: 0, name:'Mount Allison University')
    School.create!(school_id: 0, name:'Mount Royal College')
    School.create!(school_id: 0, name:'Mount St. Vincent University')
    School.create!(school_id: 0, name:'New Brunswick Community College')
    School.create!(school_id: 0, name:'New Brunswick')
    School.create!(school_id: 0, name:'Newman Theological College')
    School.create!(school_id: 0, name:'Nicola Valley Institute of Technology')
    School.create!(school_id: 0, name:'Nipissing University')
    School.create!(school_id: 0, name:'NorQuest College')
    School.create!(school_id: 0, name:'North American Baptist College')
    School.create!(school_id: 0, name:'North Island College')
    School.create!(school_id: 0, name:'North West Regional College')
    School.create!(school_id: 0, name:'Northern Alberta Institute of Technology')
    School.create!(school_id: 0, name:'Northern Lakes College')
    School.create!(school_id: 0, name:'Northern Lights Community College')
    School.create!(school_id: 0, name:'Northlands College')
    School.create!(school_id: 0, name:'Northwest Community College')
    School.create!(school_id: 0, name:'Nova Scotia Agricultural College')
    School.create!(school_id: 0, name:'Nova Scotia College of Art & Design')
    School.create!(school_id: 0, name:'Nova Scotia Community Colleges (NSCC)')
    School.create!(school_id: 0, name:'Okanagan University College')
    School.create!(school_id: 0, name:'Olds College')
    School.create!(school_id: 0, name:'Ontario Institute for Studies in Education (OISE) Regis College')
    School.create!(school_id: 0, name:'Open Learning Agency')
    School.create!(school_id: 0, name:'Parkland Regional College')
    School.create!(school_id: 0, name:'Portage College')
    School.create!(school_id: 0, name:'Prairie West Regional College')
    School.create!(school_id: 0, name:'Prince Edward Island')
    School.create!(school_id: 0, name:'Providence College and Theological Seminary Steinbach Bible College')
    School.create!(school_id: 0, name:'Queen’s Theological College')
    School.create!(school_id: 0, name:'Queen’s University')
    School.create!(school_id: 0, name:'Red Deer College')
    School.create!(school_id: 0, name:'Red River College')
    School.create!(school_id: 0, name:'Redeemer University College')
    School.create!(school_id: 0, name:'Regent College')
    School.create!(school_id: 0, name:'Renison College')
    School.create!(school_id: 0, name:'Royal Military College of Canada')
    School.create!(school_id: 0, name:'Royal Roads University')
    School.create!(school_id: 0, name:'Ryerson University')
    School.create!(school_id: 0, name:'Saint Mary’s University')
    School.create!(school_id: 0, name:'Saskatchewan Indian Federated College')
    School.create!(school_id: 0, name:'Scarborough College')
    School.create!(school_id: 0, name:'Selkirk College')
    School.create!(school_id: 0, name:'Seminary of Christ the King')
    School.create!(school_id: 0, name:'Simon Fraser University')
    School.create!(school_id: 0, name:'Sir Wilfred Grenfell College - Corner Brook Prince Edward Island')
    School.create!(school_id: 0, name:'Southern Alberta Institute of Technology')
    School.create!(school_id: 0, name:'St. Andrew’s College')
    School.create!(school_id: 0, name:'St. Augustine College')
    School.create!(school_id: 0, name:'St. Francis Xavier University')
    School.create!(school_id: 0, name:'St. Joseph’s College')
    School.create!(school_id: 0, name:'St. Lawrence College, Cornwall')
    School.create!(school_id: 0, name:'St. Paul’s College')
    School.create!(school_id: 0, name:'St. Peter’s College')
    School.create!(school_id: 0, name:'St. Peter’s Seminary')
    School.create!(school_id: 0, name:'St. Stephen’s Theologicial College')
    School.create!(school_id: 0, name:'St. Thomas More College')
    School.create!(school_id: 0, name:'St. Thomas University')
    School.create!(school_id: 0, name:'Technical University of British Columbia')
    School.create!(school_id: 0, name:'Thomas Moore Institute for Adult Education Concordia University')
    School.create!(school_id: 0, name:'Thorneloe University')
    School.create!(school_id: 0, name:'Tom Baker Cancer Centre, School of Radiation Therapy British Columbia')
    School.create!(school_id: 0, name:'Toronto School of Theology')
    School.create!(school_id: 0, name:'Trent University')
    School.create!(school_id: 0, name:'Trinity Western University')
    School.create!(school_id: 0, name:'Tyndale Bible College')
    School.create!(school_id: 0, name:'Tyndale College')
    School.create!(school_id: 0, name:'Tyndale Seminary')
    School.create!(school_id: 0, name:'Télé-université')
    School.create!(school_id: 0, name:'University College of Cape Breton')
    School.create!(school_id: 0, name:'University College of Cape Breton, Technology Campus')
    School.create!(school_id: 0, name:'University College of Emmanuel & St. Chad Alberta')
    School.create!(school_id: 0, name:'University College of the Cariboo')
    School.create!(school_id: 0, name:'University College of the Fraser Valley')
    School.create!(school_id: 0, name:'University College')
    School.create!(school_id: 0, name:'University of Alberta')
    School.create!(school_id: 0, name:'University of British Columbia - Okanagan')
    School.create!(school_id: 0, name:'University of British Columbia - Vancouver')
    School.create!(school_id: 0, name:'University of Calgary')
    School.create!(school_id: 0, name:'University of Guelph')
    School.create!(school_id: 0, name:'University of King’s College')
    School.create!(school_id: 0, name:'University of Lethbridge')
    School.create!(school_id: 0, name:'University of Manitoba St. John’s College')
    School.create!(school_id: 0, name:'University of Manitoba St. Paul’s College')
    School.create!(school_id: 0, name:'University of Manitoba University of Winnipeg')
    School.create!(school_id: 0, name:'University of Manitoba')
    School.create!(school_id: 0, name:'University of New Brunswick')
    School.create!(school_id: 0, name:'University of Northern British Columbia')
    School.create!(school_id: 0, name:'University of Ottawa')
    School.create!(school_id: 0, name:'University of Prince Edward Island')
    School.create!(school_id: 0, name:'University of Regina')
    School.create!(school_id: 0, name:'University of Saskatchewan')
    School.create!(school_id: 0, name:'University of St. Jerome’s College')
    School.create!(school_id: 0, name:'University of St. Michael’s College')
    School.create!(school_id: 0, name:'University of Toronto')
    School.create!(school_id: 0, name:'University of Trinity College')
    School.create!(school_id: 0, name:'University of Victoria')
    School.create!(school_id: 0, name:'University of Waterloo')
    School.create!(school_id: 0, name:'University of Western Ontario')
    School.create!(school_id: 0, name:'University of Windsor')
    School.create!(school_id: 0, name:'Université de Moncton')
    School.create!(school_id: 0, name:'Université de Montréal')
    School.create!(school_id: 0, name:'Université de Sherbrooke')
    School.create!(school_id: 0, name:'Université de Sudbury')
    School.create!(school_id: 0, name:'Université du Québec en Abitibi-Témiscamingue Université Laval')
    School.create!(school_id: 0, name:'Université du Québec en Outaouais')
    School.create!(school_id: 0, name:'Université du Québec à Chicoutimi')
    School.create!(school_id: 0, name:'Université du Québec à Montréal')
    School.create!(school_id: 0, name:'Université du Québec à Rimouski')
    School.create!(school_id: 0, name:'Université du Québec à Trois-Rivières')
    School.create!(school_id: 0, name:'Université du Québec')
    School.create!(school_id: 0, name:'Université Saint-Paul')
    School.create!(school_id: 0, name:'Université Sainte-Anne')
    School.create!(school_id: 0, name:'Vancouver Community College')
    School.create!(school_id: 0, name:'Vancouver School of Theology')
    School.create!(school_id: 0, name:'Victoria University')
    School.create!(school_id: 0, name:'Wilfrid Laurier Seminary')
    School.create!(school_id: 0, name:'Wilfrid Laurier University')
    School.create!(school_id: 0, name:'Wycliffe College')
    School.create!(school_id: 0, name:'Yellowquill College')
    School.create!(school_id: 0, name:'York University')
    School.create!(school_id: 0, name:'Yukon College')
    School.create!(school_id: 0, name:'Yukon Territory')
    School.create!(school_id: 0, name:'École des Hautes Études Commerciales')
    School.create!(school_id: 0, name:'École Polytechnique')
        
   
  end
end
